version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8.9-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - VOL:/path/to/mount1
      - ./resources:/opt/resources
    tmpfs:
      - /var/lib/rabbitmq
    networks:
      mynetwork:
        ipv4_address: 172.16.0.2

  clickhouse:
    container_name: clickhouse
    # build:
    #   context: ./docker
    #   dockerfile: DockerFile
    image: clickhouse/clickhouse-server:latest
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - VOL:/path/to/mount2
      - ./resources/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./resources/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/docker-entrypoint.sh
    tmpfs:
      - /var/lib/clickhouse
    ports:
      - 9000:9000
      - 8123:8123
    #command: bash -c "cat /docker-entrypoint-initdb.d/init.sql | clickhouse-client -m -n"
    networks:
      mynetwork:
        ipv4_address: 172.16.0.3
    depends_on:
      - "rabbitmq"

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
volumes:
  VOL:
    name: VOL